# Generated by Django 6.0.2 on 2026-02-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
