# Generated by Django 6.0.2 on 2026-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0002_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BinaryField(max_length=10),
        ),
    ]
