# Generated by Django 6.0.2 on 2026-02-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serialization', '0002_category_menuitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
    ]
